### ISSUE TITLE
SPM fails to build Shout: libssh2.h not found

### ISSUE THREAD

**Issue by beefon** [jakeheis/Shout#14]
On a relatively clean setup I get this error right after I embed Shout as a dep in my `Package.swift`:

![2018-06-19 11 55 29](https://user-images.githubusercontent.com/640610/41587375-c600e282-73b7-11e8-8a00-1b57a3b4cc1c.png)

`swift build` also fails with similar error.

**Comment by beefon** [comment]
Actually this is duplicate of issue #12. My bad I didn't look into closed issues. :( `brew install libssh2` fixed the build.

**Comment by beefon** [comment]
<img width="180" alt="2018-05-22 16 48 37" src="https://user-images.githubusercontent.com/640610/41587628-4eed7bbe-73b8-11e8-9e62-e167de0e5fe5.png">

**Comment by Usipov** [comment]
I also had to reboot my computer after running `brew install libssh2`

**Comment by LilianDubois** [comment]
Same issue ... 
Any solution ?
