### ISSUE TITLE
Installation through Swift Package Manager

### ISSUE THREAD

**Issue by PlaceRem** [jakeheis/Shout#16]
I have added a dependency in Package.swift file.

// swift-tools-version:4.0
// Managed by ice

import PackageDescription

let package = Package(
    name: "My app",
    products: [
        .library(name: "My app", targets: ["My app"]),
    ],
    dependencies: [
        .package(url: "https://github.com/jakeheis/Shout", from: "0.4.3"),
    ],
    targets: [
        .target(name: "My app", dependencies: ["Shout"]),
        .testTarget(name: "My appTests", dependencies: ["My app"]),
    ]
)

After that I am trying to "import Shout" in my project. But Xcode says "No such module 'Shout'".
What am I doing wrong?

**Comment by cipi1965** [comment]
Have you tried compiling at least one time?

**Comment by PlaceRem** [comment]
@cipi1965 Yes, sure. I wrote about this in detail on [reddit](https://www.reddit.com/r/swift/comments/9gljlc/cant_import_packages_using_swift_package_manager/)

**Comment by cipi1965** [comment]
@PlaceRem I can't see the post (removed)

**Comment by PlaceRem** [comment]
I have issues with importing a package into a project. Using Xcode 9 and swift 4.1.2. 
Here are my actions step by step:

1. Initiated project using `swift package init --type executable`

2. Changed `Package.swift`:

```
// swift-tools-version:4.0
// Managed by ice

import PackageDescription

let package = Package(
    name: "My app",
    products: [
        .library(name: "My app", targets: ["My app"]),
    ],
    dependencies: [
        .package(url: "https://github.com/jakeheis/Shout", from: "0.4.3"),
    ],
    targets: [
        .target(name: "My app", dependencies: ["Shout"]),
        .testTarget(name: "My appTests", dependencies: ["My app"]),
    ]
)
```

3. Run `swift build && swift package generate-xcodeproj`

4. When I open project in Xcode and try to import Shout, I'm getting `No such module 'Shout'` error message

5. I have no errors when I am running `swift build` in terminal

Folders `.build\checkouts `and `.build\repositories` contain packages folders and corresponding files.

**Comment by jakeheis** [comment]
Are you importing `Shout` in your "My app" target or "My appTests" target? You should be able to import it in your main target since you declared Shout as a dependency in your `Package.swift` but it should error if you try to import `Shout` in your test target. Could you also post the output of `swift build`?

**Comment by jakeheis** [comment]
Closing for now -- feel free to reopen with more info
