### ISSUE TITLE
Issue authenticating with private key

### ISSUE THREAD

**Issue by jnewc** [jakeheis/Shout#27]
When I try to authenticate using private + public key, it causes the terminal to irrecoverably hang (even CTRL+C and CTRL+D don't allow exiting of the process).

I'm able to auth fine with username + password and then send files via SCP.

I know this is quite a specific issue but any advice is appreciated!

EDIT: I'm running on MacOS Mojave (10.14.5) using Swift 5.

**Comment by jakeheis** [comment]
Apologies for the delayed response. I haven't seen this before, could you post your code? Seeing the actual code may make it easier to diagnose the issue

**Comment by jakeheis** [comment]
Closing for now, feel free to reopen with code / more details!
