### ISSUE TITLE
Unable to properly setup libssh

### ISSUE THREAD

**Issue by jandolina** [jakeheis/Shout#36]
This lib looks rad but I am stuck on square one. What is the proper way to add libssh to my Xcode project so that Shout can find it?

**Comment by DomAmato** [comment]
Goona echo this, I believe its expecting a package manager in order to install libssh2 but some documentation around how to do this without a package manager would be nice.

**Comment by CASNetlink** [comment]
Similar problem here. When I compiled my project XCode suggested I run 'brew install libssh2'. I did that and if I re-run that command it's telling me it is installed - 'libssh2 1.9.0_1 is already installed and up-to-date'. When compiling my app the error is 'libssh2.h' file not found. The libssh2.h is an include line in shim.h. I did add the include and lib paths for libssh2 to my project config but still no joy.

**Comment by CASNetlink** [comment]
A little more searching and messing about and I got my project to compile. I re-installed the command line tools, ran 'brew unlink libssh2 && brew link libssh2' and then closed and re-opened XCode and the compile worked.

**Comment by Klariff** [comment]
![image](https://user-images.githubusercontent.com/30582970/69759488-3dbb2a00-1130-11ea-80bc-7bb2c75e5df6.png)

yeah, somehow got using local macos libssh2, any idea?

**Comment by heidipuk** [comment]
just gonna give this a bump, since it is still an issue

**Comment by jakeheis** [comment]
See https://github.com/jakeheis/Shout/issues/34#issuecomment-621901530 -- if this does indeed fix the issue, I'll add instructions to the README how to fix this bug with Swift 5.2. The lib is only designed to work for macOS, however, so I wouldn't expect this to work in projects targeting iOS

**Comment by jakeheis** [comment]
Added instructions to README -- if any follow up is needed, I'll keep #34 open
