### ISSUE TITLE
Failed getting banner (code 43 = socketRecv)

### ISSUE THREAD

**Issue by klmitchell2** [jakeheis/Shout#42]
Im receiving this error intermittently on some jailbroken iOS devices while sting via localhost. Re-attaching the device usually fixes the issue but not always. 

Error: Failed getting banner (code 43 = socketRecv)
  - kind : Shout.SSHError.Kind.socketRecv
  - message : "Failed getting banner"

**Comment by jakeheis** [comment]
I'm afraid this is likely an issue with libssh2, not Shout. I'd recommend opening an issue in https://github.com/libssh2/libssh2 to see if anyone has tips there for working with jailbroken iOS devices
