### ISSUE TITLE
How to add Shout dependency ?

### ISSUE THREAD

**Issue by nitinchouhan123** [jakeheis/Shout#5]
Hi 

I am new to xcode. Please can you let me know how to add the Shout dependency ?
Step by Step instructions would really help me.

Thanks.

**Comment by brntphish** [comment]
Try the links here for a walkthrough of how Swift Package Manager works.

https://swift.org/getting-started/#using-the-package-manager

https://www.raywenderlich.com/148832/introduction-swift-package-manager

**Comment by jakeheis** [comment]
Apologies for not responding to this quick, thanks to @brntphish for the links! If there's demand for it I could create podspec (for CocoaPods) for it, but for now I think using SPM with the links above should be sufficient for most use cases
