### ISSUE TITLE
can we send the command "nano" or "touch" to create and put the string into the created file?

### ISSUE THREAD

**Issue by mdfalcon104** [jakeheis/Shout#51]
I am wondering whether this library can send any string into the nano or touch command to the remote server?

**Comment by JamesD4** [comment]
Hey!
Sorry to reply not-so directly, but have you considered using 'echo' and redirecting the output to said file?
For example...
```bash
echo 'james' > myname
```
Technically you could probably spin up a full TTY and automate nano but there's really no need in most situations unless you're trying to do something extremely specific.

--James
(I'm also not the dev of this repository. Just chipping in 👍 )

**Comment by jakeheis** [comment]
I echo what @DuffyAPP-IT said above! I'll mark this as resolved
