### ISSUE TITLE
Cannot use it in Xcode13, macOS 12

### ISSUE THREAD

**Issue by underthestars-zhy** [jakeheis/Shout#57]
ld: warning: Could not find or use auto-linked library 'ssh2'
Undefined symbols for architecture x86_64:
  "_libssh2_agent_connect", referenced from:
      _$s5Shout5AgentC7connectyyKF in Agent.swift.o
  "_libssh2_agent_disconnect", referenced from:
      _$s5Shout5AgentCfd in Agent.swift.o
  "_libssh2_agent_free", referenced from:
      _$s5Shout5AgentCfd in Agent.swift.o
  "_libssh2_agent_get_identity", referenced from:
      _$s5Shout5AgentC11getIdentity4lastAC9PublicKeyCSgAH_tKF in Agent.swift.o
  "_libssh2_agent_init", referenced from:
      _$s5Shout5AgentC8cSessionACs13OpaquePointerV_tKcfc in Agent.swift.o
  "_libssh2_agent_list_identities", referenced from:
      _$s5Shout5AgentC14listIdentitiesyyKF in Agent.swift.o
  "_libssh2_agent_userauth", referenced from:
      _$s5Shout5AgentC12authenticate8username3keySbSS_AC9PublicKeyCtF in Agent.swift.o
  "_libssh2_channel_close", referenced from:
      _$s5Shout7ChannelC5closeyyKF in Channel.swift.o
  "_libssh2_channel_free", referenced from:
      _$s5Shout7ChannelCfd in Channel.swift.o
  "_libssh2_channel_get_exit_status", referenced from:
      _$s5Shout7ChannelC10exitStatuss5Int32VyF in Channel.swift.o
  "_libssh2_channel_open_ex", referenced from:
      _$s5Shout7ChannelC16createForCommand8cSessionACs13OpaquePointerV_tKFZ in Channel.swift.o
  "_libssh2_channel_process_startup", referenced from:
      _$s5Shout7ChannelC4exec7commandySS_tKF in Channel.swift.o
  "_libssh2_channel_read_ex", referenced from:
      _$s5Shout7ChannelC8readDataAA18ReadWriteProcessorO0E6ResultOyF in Channel.swift.o
  "_libssh2_channel_request_pty_ex", referenced from:
      _$s5Shout7ChannelC10requestPty4typeySS_tKF in Channel.swift.o
  "_libssh2_channel_send_eof", referenced from:
      _$s5Shout7ChannelC7sendEOFyyKF in Channel.swift.o
  "_libssh2_channel_wait_closed", referenced from:
      _$s5Shout7ChannelC10waitClosedyyKF in Channel.swift.o
  "_libssh2_channel_wait_eof", referenced from:
      _$s5Shout7ChannelC7waitEOFyyKF in Channel.swift.o
  "_libssh2_channel_write_ex", referenced from:
      _$s5Shout7ChannelC5write4data6length2toAA18ReadWriteProcessorO0H6ResultO10Foundation4DataV_Sis5Int32VtFs0J0OySiAA8SSHErrorVGSWXEfU_ in Channel.swift.o
  "_libssh2_init", referenced from:
      _$s5Shout7SessionC10initResult33_E47B0AB8180088EC3B1503AA6C6E936FLL_WZ in Session.swift.o
  "_libssh2_scp_send64", referenced from:
      _$s5Shout7ChannelC12createForSCP8cSession8fileSize10remotePath11permissionsACs13OpaquePointerV_s5Int64VSSAA15FilePermissionsVtKFZ in Channel.swift.o
  "_libssh2_session_free", referenced from:
      _$s5Shout7SessionCfd in Session.swift.o
  "_libssh2_session_get_blocking", referenced from:
      _$s5Shout7SessionC8blockings5Int32Vvg in Session.swift.o
  "_libssh2_session_handshake", referenced from:
      _$s5Shout7SessionC9handshake4overy6SocketAFC_tKF in Session.swift.o
  "_libssh2_session_init_ex", referenced from:
      _$s5Shout7SessionCACyKcfc in Session.swift.o
  "_libssh2_session_last_errno", referenced from:
      _$s5Shout8SSHErrorV15mostRecentError7session13backupMessageACs13OpaquePointerV_SStFZ in SSHError.swift.o
  "_libssh2_session_last_error", referenced from:
      _$s5Shout8SSHErrorV4kind7session13backupMessageA2C4KindO_s13OpaquePointerVSStc33_36A87DA783DEB00A06E7AF49F9616525LlfC in SSHError.swift.o
  "_libssh2_session_set_blocking", referenced from:
      _$s5Shout7SessionC8blockings5Int32Vvs in Session.swift.o
  "_libssh2_sftp_close_handle", referenced from:
      _$s5Shout4SFTPC10SFTPHandle030_A805FF59DB65CB363C18C7BCF30A7K1ELLCfd in SFTP.swift.o
  "_libssh2_sftp_init", referenced from:
      _$s5Shout4SFTPC7session8cSessionAcA0D0C_s13OpaquePointerVtKcfc in SFTP.swift.o
  "_libssh2_sftp_mkdir_ex", referenced from:
      _$s5Shout4SFTPC15createDirectoryyySSKFs5Int32VSPys4Int8VGXEfU_ in SFTP.swift.o
  "_libssh2_sftp_open_ex", referenced from:
      _$s5Shout4SFTPC10SFTPHandle030_A805FF59DB65CB363C18C7BCF30A7K1ELLC8cSession04sftpL010remotePath5flags4mode8openTypeAFs13OpaquePointerV_ANSSs5Int32VA2PtKcfc in SFTP.swift.o
  "_libssh2_sftp_read", referenced from:
      _$s5Shout4SFTPC10SFTPHandle030_A805FF59DB65CB363C18C7BCF30A7K1ELLC4readAA18ReadWriteProcessorO0M6ResultOyF in SFTP.swift.o
  "_libssh2_sftp_readdir_ex", referenced from:
      _$s5Shout4SFTPC10SFTPHandle030_A805FF59DB65CB363C18C7BCF30A7K1ELLC7readDiryAA18ReadWriteProcessorO0N6ResultOSo09_LIBSSH2_B11_ATTRIBUTESVzF in SFTP.swift.o
  "_libssh2_sftp_rename_ex", referenced from:
      _$s5Shout4SFTPC6rename3src4dest8overrideySS_SSSbtKFs5Int32VSPys4Int8VGXEfU_AiLXEfU_ in SFTP.swift.o
  "_libssh2_sftp_rmdir_ex", referenced from:
      _$s5Shout4SFTPC15removeDirectoryyySSKFs5Int32VSPys4Int8VGXEfU_ in SFTP.swift.o
  "_libssh2_sftp_shutdown", referenced from:
      _$s5Shout4SFTPCfd in SFTP.swift.o
  "_libssh2_sftp_unlink_ex", referenced from:
      _$s5Shout4SFTPC10removeFileyySSKFs5Int32VSPys4Int8VGXEfU_ in SFTP.swift.o
  "_libssh2_sftp_write", referenced from:
      _$s5Shout4SFTPC10SFTPHandle030_A805FF59DB65CB363C18C7BCF30A7K1ELLC5writeyAA18ReadWriteProcessorO0N6ResultO10Foundation4DataVFs0P0OySiAA8SSHErrorVGSWXEfU_ in SFTP.swift.o
  "_libssh2_userauth_password_ex", referenced from:
      _$s5Shout7SessionC12authenticate8username8passwordySS_SStKF in Session.swift.o
  "_libssh2_userauth_publickey_fromfile_ex", referenced from:
      _$s5Shout7SessionC12authenticate8username10privateKey06publicF010passphraseySS_S3SSgtKF in Session.swift.o
ld: symbol(s) not found for architecture x86_64

**Comment by jhonnybonny** [comment]
> ld: warning: Could not find or use auto-linked library 'ssh2'
> Undefined symbols for architecture x86_64:
> "_libssh2_agent_connect", referenced from:
> _$s5Shout5AgentC7connectyyKF in Agent.swift.o
> "_libssh2_agent_disconnect", referenced from:
> _$s5Shout5AgentCfd in Agent.swift.o
> "_libssh2_agent_free", referenced from:
> _$s5Shout5AgentCfd in Agent.swift.o
> "_libssh2_agent_get_identity", referenced from:
> _$s5Shout5AgentC11getIdentity4lastAC9PublicKeyCSgAH_tKF in Agent.swift.o
> "_libssh2_agent_init", referenced from:
> _$s5Shout5AgentC8cSessionACs13OpaquePointerV_tKcfc in Agent.swift.o
> "_libssh2_agent_list_identities", referenced from:
> _$s5Shout5AgentC14listIdentitiesyyKF in Agent.swift.o
> "_libssh2_agent_userauth", referenced from:
> _$s5Shout5AgentC12authenticate8username3keySbSS_AC9PublicKeyCtF in Agent.swift.o
> "_libssh2_channel_close", referenced from:
> _$s5Shout7ChannelC5closeyyKF in Channel.swift.o
> "_libssh2_channel_free", referenced from:
> _$s5Shout7ChannelCfd in Channel.swift.o
> "_libssh2_channel_get_exit_status", referenced from:
> _$s5Shout7ChannelC10exitStatuss5Int32VyF in Channel.swift.o
> "_libssh2_channel_open_ex", referenced from:
> _$s5Shout7ChannelC16createForCommand8cSessionACs13OpaquePointerV_tKFZ in Channel.swift.o
> "_libssh2_channel_process_startup", referenced from:
> _$s5Shout7ChannelC4exec7commandySS_tKF in Channel.swift.o
> "_libssh2_channel_read_ex", referenced from:
> _$s5Shout7ChannelC8readDataAA18ReadWriteProcessorO0E6ResultOyF in Channel.swift.o
> "_libssh2_channel_request_pty_ex", referenced from:
> _$s5Shout7ChannelC10requestPty4typeySS_tKF in Channel.swift.o
> "_libssh2_channel_send_eof", referenced from:
> _$s5Shout7ChannelC7sendEOFyyKF in Channel.swift.o
> "_libssh2_channel_wait_closed", referenced from:
> _$s5Shout7ChannelC10waitClosedyyKF in Channel.swift.o
> "_libssh2_channel_wait_eof", referenced from:
> _$s5Shout7ChannelC7waitEOFyyKF in Channel.swift.o
> "_libssh2_channel_write_ex", referenced from:
> _$s5Shout7ChannelC5write4data6length2toAA18ReadWriteProcessorO0H6ResultO10Foundation4DataV_Sis5Int32VtFs0J0OySiAA8SSHErrorVGSWXEfU_ in Channel.swift.o
> "_libssh2_init", referenced from:
> _$s5Shout7SessionC10initResult33_E47B0AB8180088EC3B1503AA6C6E936FLL_WZ in Session.swift.o
> "_libssh2_scp_send64", referenced from:
> _$s5Shout7ChannelC12createForSCP8cSession8fileSize10remotePath11permissionsACs13OpaquePointerV_s5Int64VSSAA15FilePermissionsVtKFZ in Channel.swift.o
> "_libssh2_session_free", referenced from:
> _$s5Shout7SessionCfd in Session.swift.o
> "_libssh2_session_get_blocking", referenced from:
> _$s5Shout7SessionC8blockings5Int32Vvg in Session.swift.o
> "_libssh2_session_handshake", referenced from:
> _$s5Shout7SessionC9handshake4overy6SocketAFC_tKF in Session.swift.o
> "_libssh2_session_init_ex", referenced from:
> _$s5Shout7SessionCACyKcfc in Session.swift.o
> "_libssh2_session_last_errno", referenced from:
> _$s5Shout8SSHErrorV15mostRecentError7session13backupMessageACs13OpaquePointerV_SStFZ in SSHError.swift.o
> "_libssh2_session_last_error", referenced from:
> _$s5Shout8SSHErrorV4kind7session13backupMessageA2C4KindO_s13OpaquePointerVSStc33_36A87DA783DEB00A06E7AF49F9616525LlfC in SSHError.swift.o
> "_libssh2_session_set_blocking", referenced from:
> _$s5Shout7SessionC8blockings5Int32Vvs in Session.swift.o
> "_libssh2_sftp_close_handle", referenced from:
> _$s5Shout4SFTPC10SFTPHandle030_A805FF59DB65CB363C18C7BCF30A7K1ELLCfd in SFTP.swift.o
> "_libssh2_sftp_init", referenced from:
> _$s5Shout4SFTPC7session8cSessionAcA0D0C_s13OpaquePointerVtKcfc in SFTP.swift.o
> "_libssh2_sftp_mkdir_ex", referenced from:
> _$s5Shout4SFTPC15createDirectoryyySSKFs5Int32VSPys4Int8VGXEfU_ in SFTP.swift.o
> "_libssh2_sftp_open_ex", referenced from:
> _$s5Shout4SFTPC10SFTPHandle030_A805FF59DB65CB363C18C7BCF30A7K1ELLC8cSession04sftpL010remotePath5flags4mode8openTypeAFs13OpaquePointerV_ANSSs5Int32VA2PtKcfc in SFTP.swift.o
> "_libssh2_sftp_read", referenced from:
> _$s5Shout4SFTPC10SFTPHandle030_A805FF59DB65CB363C18C7BCF30A7K1ELLC4readAA18ReadWriteProcessorO0M6ResultOyF in SFTP.swift.o
> "_libssh2_sftp_readdir_ex", referenced from:
> _$s5Shout4SFTPC10SFTPHandle030_A805FF59DB65CB363C18C7BCF30A7K1ELLC7readDiryAA18ReadWriteProcessorO0N6ResultOSo09_LIBSSH2_B11_ATTRIBUTESVzF in SFTP.swift.o
> "_libssh2_sftp_rename_ex", referenced from:
> _$s5Shout4SFTPC6rename3src4dest8overrideySS_SSSbtKFs5Int32VSPys4Int8VGXEfU_AiLXEfU_ in SFTP.swift.o
> "_libssh2_sftp_rmdir_ex", referenced from:
> _$s5Shout4SFTPC15removeDirectoryyySSKFs5Int32VSPys4Int8VGXEfU_ in SFTP.swift.o
> "_libssh2_sftp_shutdown", referenced from:
> _$s5Shout4SFTPCfd in SFTP.swift.o
> "_libssh2_sftp_unlink_ex", referenced from:
> _$s5Shout4SFTPC10removeFileyySSKFs5Int32VSPys4Int8VGXEfU_ in SFTP.swift.o
> "_libssh2_sftp_write", referenced from:
> _$s5Shout4SFTPC10SFTPHandle030_A805FF59DB65CB363C18C7BCF30A7K1ELLC5writeyAA18ReadWriteProcessorO0N6ResultO10Foundation4DataVFs0P0OySiAA8SSHErrorVGSWXEfU_ in SFTP.swift.o
> "_libssh2_userauth_password_ex", referenced from:
> _$s5Shout7SessionC12authenticate8username8passwordySS_SStKF in Session.swift.o
> "_libssh2_userauth_publickey_fromfile_ex", referenced from:
> _$s5Shout7SessionC12authenticate8username10privateKey06publicF010passphraseySS_S3SSgtKF in Session.swift.o
> ld: symbol(s) not found for architecture x86_64

Do u fix it ? Because i have the same problem

**Comment by aehlke** [comment]
Likewise, any luck?

**Comment by bemehiser** [comment]
This is likely caused by compiling with headers from one libssh2 version, then linking a different one. I saw similar errors when my libraries were compiling with headers from Conan, then linking libraries installed by `brew`.

To solve this, I removed the brew-installed version.
