### ISSUE TITLE
Fatal error: Error raised at top level: Shout.LibSSH2Error.error(-16)

### ISSUE THREAD

**Issue by taqios** [jakeheis/Shout#7]
>>> swift build
    Compile Swift Module 'create_ssh' (1 sources)
    Linking ./.build/x86_64-apple-macosx10.10/debug/create_ssh
>>> ./.build/x86_64-apple-macosx10.10/debug/create_ssh
And now I get the error message:

     Fatal error: Error raised at top level: Shout.LibSSH2Error.error(-16): file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-900.0.69.2/src/swift/stdlib/public/core/ErrorType.swift, line 187
    Illegal instruction: 4

My main.swift:

    import Shout

    let session = try SSH.Session(host: "35.18.24.25")
    try session.authenticate(username: "taqo4", privateKey: "~/dora", passphrase: "demo")

    let (status, output) = try session.capture("pwd")

    print("status: \(status)")
    print("output: \(output)")

Do you have an idea what causes a problem? Is something more I need to install? Thanks for the help!

**Comment by taqios** [comment]
![image](https://user-images.githubusercontent.com/33234656/32503574-e02761a2-c3dd-11e7-85dc-cc23e74b3688.png)

Here is a picture of the code and terminal. Not sure if it's the google cloud virtual instance or the code that is incorrect. If I don't use private key, only username and password (for raspberry pi) the Shout library worked!

Thanks

**Comment by jakeheis** [comment]
I believe this crash means that an error is being thrown at the top level that's not being caught. IN other words, one of your `try` statements is failing and throwing an error. I suggest wrapping the calls in a do-catch block:
```swift
import Shout

do {
  let session = try SSH.Session(host: "35.18.24.25")
  try session.authenticate(username: "taqo4", privateKey: "~/dora", passphrase: "demo")

  let (status, output) = try session.capture("pwd")

  print("status: \(status)")
  print("output: \(output)")
} catch (let error) {
  print("Failed:", error);
}
```

Feel free to reopen this issue if this doesn't fix the crash!

**Comment by taqios** [comment]
I used your code and got "Failed: error(-16)" Do you know what this means? Thanks

**Comment by taqios** [comment]
How can I reopen this issue? Thx

**Comment by mbalinionut** [comment]
Hello, 

my code is:

```swift
import Shout

do {
	let session = try SSH.Session(host: "127.0.0.1")
	try session.authenticate(username: "alin", password: "password")
	
	let (status, output) = try session.capture("pwd")
	
	print("status: \(status)")
	print("output: \(output)")

} catch (let error) {
	print("Failed:", error);
}
```

And I get: Failed: error(-18)

**Comment by jakeheis** [comment]
https://github.com/jakeheis/Shout/commit/8237da058d66c854d98959211c14d9ce40a8068f adds a `message` property to the error so you should now be able to better debug your errors!
