### ISSUE TITLE
Use the Shout Framework in Cocoa application.

### ISSUE THREAD

**Issue by mbalinionut** [jakeheis/Shout#8]
Hello,

How can I export Shout as a Framework and use it in a Cocoa application?

Thanks.

**Comment by BigTows** [comment]
You can use CocoaPod..
Import BlueSocket, libssh2  from CocoaPods
And Shout import to you project

**Comment by kobzar** [comment]
Its fake!
BlueSocket try to install OpenSSL 
But after this we where got error. 
So, this method isnt worked.

**Comment by jakeheis** [comment]
For now, Shout only supports Swift package manager. I'm not sure how to go about supporting your use case, but if you find a way then a PR would definitely be appreciated!
